import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // === Criteria (C01-C33) ===
  const criteria = [
    // Category: PRIVACY_POLICY (C01-C08) — 8 criteria
    {
      code: 'C01',
      category: 'PRIVACY_POLICY',
      name: 'Existencia de politica de privacidade',
      description: 'Verificar se o site possui politica ou aviso de privacidade.',
      expectedEvidence: 'Link ou pagina acessivel contendo politica ou aviso de privacidade.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'A LGPD exige transparencia no tratamento de dados. A ausencia de politica impede que o titular saiba como seus dados sao usados.',
      improvementSuggestion: 'Criar e publicar uma politica de privacidade acessivel a partir de qualquer pagina do site.',
      weight: 3.12,
    },
    {
      code: 'C02',
      category: 'PRIVACY_POLICY',
      name: 'Mencao aos dados coletados',
      description: 'Verificar se a politica lista ou descreve os tipos de dados pessoais coletados.',
      expectedEvidence: 'Lista ou descricao dos tipos de dados pessoais coletados.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'O principio da transparencia (Art. 6, VI, LGPD) exige que o titular saiba quais dados sao coletados.',
      improvementSuggestion: 'Listar claramente todos os dados pessoais coletados (nome, e-mail, CPF, etc.).',
      weight: 3.12,
    },
    {
      code: 'C03',
      category: 'PRIVACY_POLICY',
      name: 'Mencao a finalidade',
      description: 'Verificar se a politica explica claramente o motivo da coleta de cada dado ou categoria.',
      expectedEvidence: 'Explicacao clara do motivo da coleta de cada dado ou categoria.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'O principio da finalidade (Art. 6, I, LGPD) determina que os dados sejam coletados para propositos legitimos e especificos.',
      improvementSuggestion: 'Descrever a finalidade de cada dado coletado de forma especifica e compreensivel.',
      weight: 3.12,
    },
    {
      code: 'C04',
      category: 'PRIVACY_POLICY',
      name: 'Mencao ao tempo de armazenamento',
      description: 'Verificar se a politica informa por quanto tempo os dados serao mantidos.',
      expectedEvidence: 'Informacao sobre por quanto tempo os dados serao mantidos.',
      riskIfAbsent: 'MEDIUM',
      educationalExplanation: 'O principio da necessidade (Art. 6, III, LGPD) implica que dados nao devem ser mantidos alem do necessario.',
      improvementSuggestion: 'Informar o prazo de retencao ou os criterios usados para defini-lo.',
      weight: 3.12,
    },
    {
      code: 'C05',
      category: 'PRIVACY_POLICY',
      name: 'Mencao ao compartilhamento de dados',
      description: 'Verificar se a politica informa sobre terceiros com quem os dados sao compartilhados.',
      expectedEvidence: 'Informacao sobre terceiros com quem os dados sao compartilhados.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'O titular tem direito de saber com quem seus dados sao compartilhados (Art. 9, LGPD).',
      improvementSuggestion: 'Listar categorias de terceiros e finalidades do compartilhamento.',
      weight: 3.12,
    },
    {
      code: 'C06',
      category: 'PRIVACY_POLICY',
      name: 'Mencao a bases legais',
      description: 'Verificar se a politica menciona bases legais como consentimento, execucao de contrato, obrigacao legal e legitimo interesse.',
      expectedEvidence: 'Referencias a consentimento, execucao de contrato, obrigacao legal, legitimo interesse.',
      riskIfAbsent: 'MEDIUM',
      educationalExplanation: 'Toda operacao de tratamento deve ter uma base legal valida (Art. 7, LGPD).',
      improvementSuggestion: 'Indicar quais bases legais fundamentam cada operacao de tratamento.',
      weight: 3.12,
    },
    {
      code: 'C07',
      category: 'PRIVACY_POLICY',
      name: 'Identificacao do controlador',
      description: 'Verificar se a politica identifica o controlador dos dados.',
      expectedEvidence: 'Nome da empresa, razao social, CNPJ ou identificacao equivalente.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'O titular precisa saber quem e o responsavel pelo tratamento de seus dados (Art. 6, VII, LGPD).',
      improvementSuggestion: 'Incluir identificacao completa do controlador na politica.',
      weight: 3.12,
    },
    {
      code: 'C08',
      category: 'PRIVACY_POLICY',
      name: 'Canal de contato / Encarregado (DPO)',
      description: 'Verificar se a politica disponibiliza canal de contato para questoes de privacidade.',
      expectedEvidence: 'E-mail, formulario ou outro canal para contato sobre privacidade.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'A LGPD garante ao titular o direito de obter informacoes sobre o tratamento mediante solicitacao (Art. 9, LGPD).',
      improvementSuggestion: 'Disponibilizar canal de contato claro, preferencialmente com indicacao de encarregado/DPO.',
      weight: 3.12,
    },

    // Category: COOKIES (C09-C14) — 6 criteria
    {
      code: 'C09',
      category: 'COOKIES',
      name: 'Existencia de banner de cookies',
      description: 'Verificar se o site possui banner de cookies visivel.',
      expectedEvidence: 'Elemento visual (banner, modal ou overlay) informando sobre uso de cookies.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'Cookies que nao sao estritamente necessarios exigem consentimento previo do titular (Art. 7, LGPD).',
      improvementSuggestion: 'Implementar banner de cookies visivel na primeira visita.',
      weight: 4.17,
    },
    {
      code: 'C10',
      category: 'COOKIES',
      name: 'Botao de aceitar cookies',
      description: 'Verificar se o banner possui botao ou mecanismo para aceitar cookies.',
      expectedEvidence: 'Botao ou mecanismo que permite ao titular consentir com o uso de cookies.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'O consentimento deve ser livre, informado e inequivoco (Art. 8, LGPD).',
      improvementSuggestion: 'Incluir botao claro de "Aceitar" no banner.',
      weight: 4.17,
    },
    {
      code: 'C11',
      category: 'COOKIES',
      name: 'Botao de recusar cookies',
      description: 'Verificar se o banner possui botao ou mecanismo para recusar cookies nao essenciais.',
      expectedEvidence: 'Botao ou mecanismo que permite ao titular rejeitar cookies nao essenciais.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'A LGPD garante ao titular o direito de revogar o consentimento. Recusar deve ser tao facil quanto aceitar (Art. 8, par. 5, LGPD).',
      improvementSuggestion: 'Incluir botao claro de "Recusar" ou "Recusar nao essenciais" no banner.',
      weight: 4.17,
    },
    {
      code: 'C12',
      category: 'COOKIES',
      name: 'Opcao de gerenciar preferencias',
      description: 'Verificar se o banner oferece opcao de gerenciar preferencias de cookies por categoria.',
      expectedEvidence: 'Mecanismo que permite escolher categorias de cookies individualmente.',
      riskIfAbsent: 'MEDIUM',
      educationalExplanation: 'O consentimento deve ser informado e especifico. O titular deve poder escolher quais categorias aceita.',
      improvementSuggestion: 'Oferecer painel de preferencias com categorias de cookies separadas.',
      weight: 4.17,
    },
    {
      code: 'C13',
      category: 'COOKIES',
      name: 'Link para politica de cookies/privacidade',
      description: 'Verificar se o banner possui link que direciona a politica completa de cookies ou privacidade.',
      expectedEvidence: 'Link acessivel no banner que direciona a politica completa.',
      riskIfAbsent: 'MEDIUM',
      educationalExplanation: 'O titular deve ter acesso facil a informacoes completas sobre o uso de cookies e dados.',
      improvementSuggestion: 'Incluir link visivel para a politica de privacidade ou cookies no banner.',
      weight: 4.17,
    },
    {
      code: 'C14',
      category: 'COOKIES',
      name: 'Cookies nao necessarios antes de consentimento',
      description: 'Verificar ausencia de cookies de marketing/rastreamento carregados antes do consentimento.',
      expectedEvidence: 'Ausencia de cookies de marketing/rastreamento antes do consentimento.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'Carregar cookies nao essenciais antes do consentimento viola o principio do consentimento previo (Art. 7, LGPD).',
      improvementSuggestion: 'Garantir que cookies nao essenciais so sejam carregados apos consentimento explicito.',
      weight: 4.15,
    },

    // Category: FORMS (C15-C18) — 4 criteria
    {
      code: 'C15',
      category: 'FORMS',
      name: 'Identificacao de campos de dados pessoais',
      description: 'Identificar formularios com campos de dados pessoais como nome, e-mail, telefone.',
      expectedEvidence: 'Formularios com campos como nome, e-mail, telefone, CPF, endereco.',
      riskIfAbsent: 'INFO',
      educationalExplanation: 'O sistema identifica quais dados pessoais estao sendo coletados para awareness do proprietario do site.',
      improvementSuggestion: 'Revisar se todos os campos sao realmente necessarios para a finalidade do formulario.',
      weight: 3.75,
    },
    {
      code: 'C16',
      category: 'FORMS',
      name: 'Minimizacao de dados',
      description: 'Avaliar se o formulario solicita apenas dados necessarios para a finalidade declarada.',
      expectedEvidence: 'Ausencia de campos desnecessarios para a finalidade declarada.',
      riskIfAbsent: 'MEDIUM',
      educationalExplanation: 'O principio da necessidade/minimizacao (Art. 6, III, LGPD) limita a coleta ao minimo necessario para a finalidade.',
      improvementSuggestion: 'Remover campos que nao sao estritamente necessarios para a finalidade do formulario.',
      weight: 3.75,
    },
    {
      code: 'C17',
      category: 'FORMS',
      name: 'Deteccao de dados sensiveis',
      description: 'Verificar a presenca de campos ou textos relacionados a dados sensiveis conforme LGPD.',
      expectedEvidence: 'Ausencia de campos relacionados a saude, biometria, religiao, opiniao politica, raca.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'Dados sensiveis merecem protecao especial (Art. 5, II e Art. 11, LGPD) e so podem ser coletados em situacoes especificas.',
      improvementSuggestion: 'Evitar coletar dados sensiveis a menos que haja base legal especifica e justificativa clara.',
      weight: 3.75,
    },
    {
      code: 'C18',
      category: 'FORMS',
      name: 'Aviso de privacidade no formulario',
      description: 'Verificar se ha texto informativo sobre privacidade proximo ao formulario.',
      expectedEvidence: 'Texto proximo ao formulario explicando uso dos dados coletados.',
      riskIfAbsent: 'MEDIUM',
      educationalExplanation: 'O titular deve ser informado sobre o tratamento de seus dados no momento da coleta (Art. 9, LGPD).',
      improvementSuggestion: 'Adicionar texto breve proximo ao formulario explicando finalidade e base legal da coleta.',
      weight: 3.75,
    },

    // Category: RIGHTS (C19-C24) — 6 criteria
    {
      code: 'C19',
      category: 'RIGHTS',
      name: 'Direito de acesso',
      description: 'Verificar se a politica menciona o direito de solicitar confirmacao e acesso aos dados.',
      expectedEvidence: 'Mencao ao direito de solicitar confirmacao e acesso aos dados.',
      riskIfAbsent: 'MEDIUM',
      educationalExplanation: 'O titular pode solicitar a qualquer momento a confirmacao da existencia de tratamento e acesso aos seus dados (Art. 18, I e II, LGPD).',
      improvementSuggestion: 'Incluir na politica descricao clara do direito de acesso e como exerce-lo.',
      weight: 2.5,
    },
    {
      code: 'C20',
      category: 'RIGHTS',
      name: 'Direito de correcao',
      description: 'Verificar se a politica menciona o direito de solicitar correcao de dados.',
      expectedEvidence: 'Mencao ao direito de solicitar correcao de dados incompletos ou incorretos.',
      riskIfAbsent: 'MEDIUM',
      educationalExplanation: 'O titular pode pedir a correcao de dados inexatos (Art. 18, III, LGPD).',
      improvementSuggestion: 'Descrever na politica como o titular pode solicitar correcao.',
      weight: 2.5,
    },
    {
      code: 'C21',
      category: 'RIGHTS',
      name: 'Direito de exclusao',
      description: 'Verificar se a politica menciona o direito de solicitar exclusao de dados.',
      expectedEvidence: 'Mencao ao direito de solicitar exclusao de dados.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'O titular pode pedir a eliminacao de dados tratados com consentimento (Art. 18, V, LGPD).',
      improvementSuggestion: 'Incluir na politica informacao sobre como solicitar exclusao de dados.',
      weight: 2.5,
    },
    {
      code: 'C22',
      category: 'RIGHTS',
      name: 'Direito de portabilidade',
      description: 'Verificar se a politica menciona o direito de portabilidade dos dados.',
      expectedEvidence: 'Mencao ao direito de solicitar portabilidade dos dados.',
      riskIfAbsent: 'MEDIUM',
      educationalExplanation: 'O titular pode pedir a portabilidade a outro fornecedor (Art. 18, V, LGPD).',
      improvementSuggestion: 'Descrever na politica o direito de portabilidade e como solicita-lo.',
      weight: 2.5,
    },
    {
      code: 'C23',
      category: 'RIGHTS',
      name: 'Direito de revogacao do consentimento',
      description: 'Verificar se a politica menciona o direito de revogar o consentimento a qualquer momento.',
      expectedEvidence: 'Mencao ao direito de revogar o consentimento a qualquer momento.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'O consentimento pode ser revogado a qualquer momento (Art. 8, par. 5, LGPD).',
      improvementSuggestion: 'Incluir na politica informacao clara sobre como revogar o consentimento.',
      weight: 2.5,
    },
    {
      code: 'C24',
      category: 'RIGHTS',
      name: 'Direito de informacao sobre compartilhamento',
      description: 'Verificar se a politica menciona o direito de saber com quem os dados sao compartilhados.',
      expectedEvidence: 'Mencao ao direito de saber com quem os dados sao compartilhados.',
      riskIfAbsent: 'MEDIUM',
      educationalExplanation: 'O titular pode solicitar informacoes sobre compartilhamento com terceiros (Art. 18, VII, LGPD).',
      improvementSuggestion: 'Descrever na politica as informacoes sobre compartilhamento e como obte-las.',
      weight: 2.5,
    },

    // Category: CONTROLLER (C25-C27) — 3 criteria
    {
      code: 'C25',
      category: 'CONTROLLER',
      name: 'Identificacao do controlador',
      description: 'Verificar se o site identifica o controlador dos dados pessoais.',
      expectedEvidence: 'Nome/razao social, CNPJ ou identificacao equivalente.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'O controlador e a pessoa responsavel pelo tratamento de dados. O titular precisa saber quem e (Art. 5, VI, LGPD).',
      improvementSuggestion: 'Incluir identificacao completa do controlador na politica.',
      weight: 3.33,
    },
    {
      code: 'C26',
      category: 'CONTROLLER',
      name: 'Canal de contato para privacidade',
      description: 'Verificar se ha canal de contato dedicado a questoes de privacidade.',
      expectedEvidence: 'E-mail, formulario ou outro canal dedicado a questoes de privacidade.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'E essencial que o titular tenha um canal claro para exercer seus direitos e tirar duvidas (Art. 9, LGPD).',
      improvementSuggestion: 'Disponibilizar e-mail ou formulario de contato dedicado a privacidade.',
      weight: 3.33,
    },
    {
      code: 'C27',
      category: 'CONTROLLER',
      name: 'Indicacao de encarregado (DPO)',
      description: 'Verificar se ha indicacao de encarregado pelo tratamento de dados.',
      expectedEvidence: 'Nome ou contato do encarregado pelo tratamento de dados.',
      riskIfAbsent: 'MEDIUM',
      educationalExplanation: 'A ANPD pode determinar a nomeacao de um encarregado. A indicacao e uma boa pratica.',
      improvementSuggestion: 'Indicar o encarregado/DPO com canal de contato direto.',
      weight: 3.34,
    },

    // Category: SECURITY (C28-C31) — 4 criteria
    {
      code: 'C28',
      category: 'SECURITY',
      name: 'Uso de HTTPS',
      description: 'Verificar se o site utiliza HTTPS com certificado SSL/TLS valido.',
      expectedEvidence: 'Certificado SSL/TLS valido e ativo.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'O principio da seguranca (Art. 46, LGPD) exige medidas para proteger dados de acessos nao autorizados. HTTPS e o minimo esperado.',
      improvementSuggestion: 'Instalar certificado SSL/TLS e garantir que todas as paginas usem HTTPS.',
      weight: 2.5,
    },
    {
      code: 'C29',
      category: 'SECURITY',
      name: 'Formularios em paginas seguras',
      description: 'Verificar se formularios estao presentes em paginas servidas via HTTPS.',
      expectedEvidence: 'Formularios presentes apenas em paginas servidas via HTTPS.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'Formularios que coletam dados pessoais devem estar em paginas seguras para evitar interceptacao.',
      improvementSuggestion: 'Migrar todas as paginas com formularios para HTTPS.',
      weight: 2.5,
    },
    {
      code: 'C30',
      category: 'SECURITY',
      name: 'Ausencia de dados sensiveis expostos',
      description: 'Verificar se nao ha dados sensiveis visiveis no codigo-fonte ou conteudo publico.',
      expectedEvidence: 'Nenhum dado sensivel visivel no codigo-fonte ou conteudo publico.',
      riskIfAbsent: 'HIGH',
      educationalExplanation: 'Dados sensiveis expostos publicamente representam risco significativo de violacao e incidente de seguranca.',
      improvementSuggestion: 'Nunca expor dados sensiveis no HTML, JavaScript ou conteudo publico.',
      weight: 2.5,
    },
    {
      code: 'C31',
      category: 'SECURITY',
      name: 'Scripts externos relevantes',
      description: 'Listar scripts de terceiros carregados pela pagina.',
      expectedEvidence: 'Lista de scripts de terceiros carregados pela pagina.',
      riskIfAbsent: 'INFO',
      educationalExplanation: 'Scripts de terceiros podem coletar dados dos visitantes. E importante conhecer quais estao presentes no site.',
      improvementSuggestion: 'Revisar periodicamente os scripts de terceiros e remover os desnecessarios.',
      weight: 2.5,
    },

    // Category: LANGUAGE (C32-C33) — 2 criteria
    {
      code: 'C32',
      category: 'LANGUAGE',
      name: 'Ausencia de termos excessivamente genericos',
      description: 'Verificar se a politica evita termos vagos ou excessivamente genericos.',
      expectedEvidence: 'Politica com descricoes especificas em vez de frases vagas.',
      riskIfAbsent: 'MEDIUM',
      educationalExplanation: 'Frases como "usamos dados para melhorar sua experiencia" sem detalhamento violam o principio de transparencia e dificultam o entendimento do titular.',
      improvementSuggestion: 'Substituir termos genericos por descricoes especificas de dados, finalidades e procedimentos.',
      weight: 2.5,
    },
    {
      code: 'C33',
      category: 'LANGUAGE',
      name: 'Clareza e acessibilidade do texto',
      description: 'Verificar se a politica e escrita em linguagem compreensivel para o publico geral.',
      expectedEvidence: 'Politica escrita em linguagem compreensivel para o publico geral.',
      riskIfAbsent: 'MEDIUM',
      educationalExplanation: 'A LGPD exige que informacoes ao titular sejam claras e acessiveis (Art. 9, par. 1, LGPD).',
      improvementSuggestion: 'Revisar a politica para usar linguagem simples, direta e acessivel ao publico geral.',
      weight: 2.5,
    },
  ];

  for (const criterion of criteria) {
    await prisma.criterion.upsert({
      where: { code: criterion.code },
      update: criterion,
      create: criterion,
    });
  }
  console.log(`Seeded ${criteria.length} criteria records.`);

  // === Glossary Terms (15+ terms) ===
  const glossaryTerms = [
    {
      term: 'Titular',
      definition: 'Pessoa natural a quem se referem os dados pessoais que sao objeto de tratamento.',
      lgpdArticle: 'Art. 5, V',
      relatedTerms: '["Dado pessoal", "Controlador", "Tratamento"]',
    },
    {
      term: 'Dado pessoal',
      definition: 'Informacao relacionada a pessoa natural identificada ou identificavel.',
      lgpdArticle: 'Art. 5, I',
      relatedTerms: '["Titular", "Dado sensivel", "Tratamento"]',
    },
    {
      term: 'Dado sensivel',
      definition: 'Dado pessoal sobre origem racial ou etnica, conviccao religiosa, opiniao politica, filiacao a sindicato ou a organizacao de carater religioso, filosofico ou politico, dado referente a saude ou a vida sexual, dado genetico ou biometrico.',
      lgpdArticle: 'Art. 5, II',
      relatedTerms: '["Dado pessoal", "Consentimento", "Tratamento"]',
    },
    {
      term: 'Tratamento',
      definition: 'Toda operacao realizada com dados pessoais, como coleta, producao, recepcao, classificacao, utilizacao, acesso, reproducao, transmissao, distribuicao, processamento, arquivamento, armazenamento, eliminacao, avaliacao ou controle da informacao, modificacao, comunicacao, transferencia, difusao ou extracao.',
      lgpdArticle: 'Art. 5, X',
      relatedTerms: '["Dado pessoal", "Controlador", "Operador"]',
    },
    {
      term: 'Controlador',
      definition: 'Pessoa natural ou juridica, de direito publico ou privado, a quem competem as decisoes referentes ao tratamento de dados pessoais.',
      lgpdArticle: 'Art. 5, VI',
      relatedTerms: '["Operador", "Encarregado", "Tratamento"]',
    },
    {
      term: 'Operador',
      definition: 'Pessoa natural ou juridica, de direito publico ou privado, que realiza o tratamento de dados pessoais em nome do controlador.',
      lgpdArticle: 'Art. 5, VII',
      relatedTerms: '["Controlador", "Tratamento", "Encarregado"]',
    },
    {
      term: 'Encarregado (DPO)',
      definition: 'Pessoa indicada pelo controlador e operador para atuar como canal de comunicacao entre o controlador, os titulares dos dados e a Autoridade Nacional de Protecao de Dados (ANPD).',
      lgpdArticle: 'Art. 5, VIII',
      relatedTerms: '["Controlador", "Operador", "ANPD"]',
    },
    {
      term: 'Consentimento',
      definition: 'Manifestacao livre, informada e inequivoca pela qual o titular concorda com o tratamento de seus dados pessoais para uma finalidade determinada.',
      lgpdArticle: 'Art. 5, XII',
      relatedTerms: '["Titular", "Tratamento", "Finalidade", "Revogacao"]',
    },
    {
      term: 'Finalidade',
      definition: 'Proposito legitimo, especifico, explicito e informado ao titular para o qual os dados pessoais serao tratados.',
      lgpdArticle: 'Art. 6, I',
      relatedTerms: '["Tratamento", "Consentimento", "Necessidade"]',
    },
    {
      term: 'Necessidade',
      definition: 'Limitacao do tratamento ao minimo necessario para a realizacao de suas finalidades, com abrangencia dos dados pertinentes, proporcionais e nao excessivos.',
      lgpdArticle: 'Art. 6, III',
      relatedTerms: '["Finalidade", "Tratamento", "Minimizacao"]',
    },
    {
      term: 'ANPD',
      definition: 'Autoridade Nacional de Protecao de Dados, orgao da administracao publica responsavel por zelar, implementar e fiscalizar o cumprimento da LGPD em todo o territorio nacional.',
      lgpdArticle: 'Art. 5, XIX',
      relatedTerms: '["LGPD", "Sancao", "Encarregado"]',
    },
    {
      term: 'LGPD',
      definition: 'Lei Geral de Protecao de Dados Pessoais (Lei no 13.709/2018), que dispoe sobre o tratamento de dados pessoais, inclusive nos meios digitais, por pessoa natural ou por pessoa juridica de direito publico ou privado, com o objetivo de proteger os direitos fundamentais de liberdade e de privacidade e o livre desenvolvimento da personalidade da pessoa natural.',
      lgpdArticle: 'Art. 1',
      relatedTerms: '["ANPD", "Dado pessoal", "Tratamento"]',
    },
    {
      term: 'Bases legais',
      definition: 'Hipoteses previstas na LGPD que autorizam o tratamento de dados pessoais, como consentimento, execucao de contrato, obrigacao legal, legitimo interesse, entre outras.',
      lgpdArticle: 'Art. 7',
      relatedTerms: '["Consentimento", "Tratamento", "Legitimo interesse"]',
    },
    {
      term: 'Cookie',
      definition: 'Pequeno arquivo armazenado no navegador do usuario que permite a um site lembrar informacoes sobre a visita, preferencias ou estado de autenticacao.',
      lgpdArticle: null,
      relatedTerms: '["Consentimento", "Dado pessoal", "Banner"]',
    },
    {
      term: 'Relatorio de impacto',
      definition: 'Documentacao do controlador que contem a descricao dos processos de tratamento de dados pessoais que podem gerar riscos as liberdades civis e aos direitos fundamentais.',
      lgpdArticle: 'Art. 5, XVII',
      relatedTerms: '["Controlador", "Tratamento", "Risco"]',
    },
  ];

  for (const term of glossaryTerms) {
    await prisma.glossaryTerm.upsert({
      where: { term: term.term },
      update: term,
      create: term,
    });
  }
  console.log(`Seeded ${glossaryTerms.length} glossary term records.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
